version: '3.8'

services:

  haxball:
    build:
      context: .
    network_mode: "host"
    restart: always
    volumes:
      - ./config:/app/config
      - browser-data:/app/userdatadir


volumes:
  browser-data:
