services:

  haxball:
    build:
      context: .
    network_mode: "host"
    restart: always
    volumes:
      - ./config.json:/app/config.json
      - browser-data:/app/userdatadir


volumes:
  browser-data:
